export default {
  employees: [],
  selectedEmployee: {},
  table: {
    columns: [
      { title: 'Name', field: 'employeeName', visible: true },
      { title: 'Position', field: 'positionName', visible: true },
      { title: 'Employment Type', field: 'employmentTypeName', visible: true },
    ],
    list: [],
    meta: {
      isPaginated: true,
      backendPagination: true,
      backendSorting: false,
      isEmpty: false,
      isStriped: false,
      isHoverable: true,
      hasMobileCards: true,
      isPaginationSimple: true,
      isPaginationRounded: false,
      paginationPosition: 'bottom',
      defaultSortDirection: 'asc',
      defaultSortColumn: 'name',
      sortIcon: 'arrow-up',
      sortIconSize: 'is-small',
      current_page: 1,
      per_page: 10,
    },
  },
};
