export default {
  scheduleList: [
    'Accounting Dept. Schedule',
    'HR Dept. Schedule',
    'IT Dept. Schedule',
    'Sales Dept. Schedule',
    'Marketing Dept. Schedule',
  ],
  table: {
    columns: [
      {
        title: 'Schedule ID', field: 'scheduleId', visible: true, centered: false, sortable: true, custom: false,
      },
      {
        title: 'Schedule Name', field: 'scheduleName', visible: true, centered: false, sortable: true, custom: false,
      },
      {
        title: 'Remarks', field: 'remarks', visible: true, centered: false, sortable: false, custom: false,
      },
      {
        title: 'Status', field: 'status', visible: true, centered: true, sortable: true, custom: true,
      },
    ],
    list: [
      {
        scheduleId: 'COMP1SCHED1',
        scheduleName: 'Accounting Dept. Schedule',
        remarks: '',
        status: true,
      },
      {
        scheduleId: 'COMP1SCHED2',
        scheduleName: 'HR Dept. Schedule',
        remarks: '',
        status: true,
      },
      {
        scheduleId: 'COMP1SCHED3',
        scheduleName: 'IT Dept. Schedule',
        remarks: '',
        status: true,
      },
      {
        scheduleId: 'COMP1SCHED4',
        scheduleName: 'Sales Dept. Schedule',
        remarks: '',
        status: true,
      },
      {
        scheduleId: 'COMP1SCHED5',
        scheduleName: 'Marketing Dept. Schedule',
        remarks: '',
        status: true,
      },
    ],
    meta: {
      isEmpty: false,
      isStriped: false,
      isHoverable: true,
      hasMobileCards: true,
      isPaginated: true,
      isPaginationSimple: true,
      isPaginationRounded: false,
      paginationPosition: 'bottom',
      defaultSortDirection: 'asc',
      defaultSortColumn: 'name',
      sortIcon: 'arrow-up',
      sortIconSize: 'is-small',
      currentPage: 1,
      perPage: 10,
    },
  },
  addSchedule: {
    columns: [
      {
        title: 'Day', field: 'day', visible: true, centered: false, sortable: true, custom: false,
      },
      {
        title: 'Time In & Time Out', field: 'timeIn', visible: true, centered: true, sortable: false, custom: true,
      },
      {
        title: 'Morning Break Time', field: 'morningBreak', visible: true, centered: true, sortable: false, custom: true,
      },
      {
        title: 'Lunch Break Time', field: 'lunchBreak', visible: true, centered: true, sortable: false, custom: true,
      },
      {
        title: 'Afternoon Break Time', field: 'afternoonBreak', visible: true, centered: true, sortable: false, custom: true,
      },
      {
        title: '', field: 'edit', visible: true, centered: true, sortable: false, custom: true,
      },
    ],
    list: [
      {
        day: 'MONDAY',
        timeIn: null,
        timeOut: null,
        morningBreakIn: null,
        morningBreakOut: null,
        lunchBreakIn: null,
        lunchBreakOut: null,
        afternoonBreakIn: null,
        afternoonBreakOut: null,
      },
      {
        day: 'TUESDAY',
        timeIn: null,
        timeOut: null,
        morningBreakIn: null,
        morningBreakOut: null,
        lunchBreakIn: null,
        lunchBreakOut: null,
        afternoonBreakIn: null,
        afternoonBreakOut: null,
      },
      {
        day: 'WEDNESDAY',
        timeIn: null,
        timeOut: null,
        morningBreakIn: null,
        morningBreakOut: null,
        lunchBreakIn: null,
        lunchBreakOut: null,
        afternoonBreakIn: null,
        afternoonBreakOut: null,
      },
      {
        day: 'THURSDAY',
        timeIn: null,
        timeOut: null,
        morningBreakIn: null,
        morningBreakOut: null,
        lunchBreakIn: null,
        lunchBreakOut: null,
        afternoonBreakIn: null,
        afternoonBreakOut: null,
      },
      {
        day: 'FRIDAY',
        timeIn: null,
        timeOut: null,
        morningBreakIn: null,
        morningBreakOut: null,
        lunchBreakIn: null,
        lunchBreakOut: null,
        afternoonBreakIn: null,
        afternoonBreakOut: null,
      },
      {
        day: 'SATURDAY',
        timeIn: null,
        timeOut: null,
        morningBreakIn: null,
        morningBreakOut: null,
        lunchBreakIn: null,
        lunchBreakOut: null,
        afternoonBreakIn: null,
        afternoonBreakOut: null,
      },
      {
        day: 'SUNDAY',
        timeIn: null,
        timeOut: null,
        morningBreakIn: null,
        morningBreakOut: null,
        lunchBreakIn: null,
        lunchBreakOut: null,
        afternoonBreakIn: null,
        afternoonBreakOut: null,
      },
    ],
    meta: {
      isEmpty: false,
      isStriped: false,
      isHoverable: true,
      hasMobileCards: true,
      isPaginated: false,
      isPaginationSimple: true,
      isPaginationRounded: false,
      paginationPosition: 'bottom',
      defaultSortDirection: 'asc',
      defaultSortColumn: 'name',
      sortIcon: 'arrow-up',
      sortIconSize: 'is-small',
      currentPage: 1,
      perPage: 10,
    },
  },
};
